name: Test and Deploy
on: 
  push:
    branches:
      - cicd-prepping

jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello
        run: echo 'hi there!'
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout and clone repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: setup postgresql
        uses: harmon758/postgresql-action@v1
        with:
          pg database: test_db
          pg user: Ms_Theresa_Est
          pg password: pazzwurd1!
          run: PGDATABASE=test_db PGUSER=Ms_Theresa_Est PGPASSWORD pazzwurd1! npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: checkout and clone repo
        uses: actions/checkout@v3
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

