name: Test and Deploy

on:
  push:
    branches:
      - main


jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello!"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: clone and checkout
        uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v3
      - name: use postgresql
        uses: harmon758/postgresql-action@v1
        with: 
          postgresql user: Tests_Daily
          postgresql db: test_db
          postgresql password: "password"
      - name: install dependencies
        run: npm i
      - name: run tests
        run: PGDATABASE=test_db PGUSER=Tests_Daily PGPASSWORD=password