name: Test and deploy

on: 
  push:
    branches: 
      - cicd-prepping
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hi there 2'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_snacks
          postgresql user: Ms_Theresa_Est
          postgresql password: blorpbloop
          postgresql port: 5432
      - name: Run Integration Tests
        run: PGDATABASE=nc_snacks PG_PORT=5432 PGUSER=Ms_Theresa_Est PGPASSWORD=blorpbloop npm test
        
